apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retail-model
  template:
    metadata:
      labels:
        app: retail-model
    spec:
      containers:
      - name: retail-model
        image: gcr.io/charismatic-age-451204-v4/retail-model:latest
        ports:
        - containerPort: 5000
