name: MLOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: pip install -r requirements.txt

  data-injection:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Load Data into BigQuery
        run: python src/data_injection.py

  feature-engineering:
    runs-on: ubuntu-latest
    needs: data-injection
    steps:
      - name: Run Feature Engineering
        run: python src/featureengineering.py

  model-training:
    runs-on: ubuntu-latest
    needs: feature-engineering
    steps:
      - name: Train Model
        run: python src/model_training.py

  model-registry:
    runs-on: ubuntu-latest
    needs: model-training
    steps:
      - name: Register Model
        run: python src/model_registry.py

  build-and-push:
    runs-on: ubuntu-latest
    needs: model-registry
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate with Google Container Registry
        run: echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/charismatic-age-451204-v4/retail-model:latest .
          docker push gcr.io/charismatic-age-451204-v4/retail-model:latest

  deploy-to-gke:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Kubernetes CLI
        run: |
          gcloud container clusters get-credentials retail-cluster --zone us-central1-a --project charismatic-age-451204-v4

      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment/deployment.yaml
          kubectl apply -f deployment/service.yaml
